package com.SOEN6441_DND.Controller;

import java.lang.reflect.Array;
import java.util.Arrays;

/**
 * This Class calculates Dice Rolls Value based on different types of dice Ex.
 * 4d6, 6d8 etc..
 * 
 * @author Punit Trivedi
 * @author Appan Chhibber
 *
 */
public class DiceRollController {

	public int counter;// No of times Dice should roll. Ex. 4d6 Counter = 4;
	public int maxDiceValue; // Maximum value of Single Dice. Ex. 4d6
								// maxDiceValue = 6;
	public int maxTotal;
	public int total;
	public int diceResult[];
	public int sortedRevDiceList[] = new int[6];

	/**
	 * This constructor inputs takes input the dice value and counter to be used
	 * for calculating the result of the dice rolled.
	 * 
	 * @param counter
	 * @param maxDiceValue
	 */
	public DiceRollController(int counter, int maxDiceValue) {
		this.counter = counter;
		this.maxDiceValue = maxDiceValue;
		this.maxTotal = maxDiceValue;
		total = 0;
		this.diceResult = new int[counter];
	}

	/**
	 * This function calculates the dice result based on the random number
	 * generated by random() function
	 * 
	 * @return diceResult Returns the calculated the dice rolled value.
	 */
	public int getDiceRollResult() {
		total = 0;
		for (int i = 0; i < counter; i++) {
			diceResult[i] = 1 + (int) (Math.random() * (maxTotal));
			if (diceResult[i] > maxTotal) {
				diceResult[i] = maxTotal;
			}
		}
		Arrays.sort(diceResult);
		if (counter == 1) {
			return diceResult[0];
		}
		for (int i = (counter - 1); i > 0; i--) {
			total += diceResult[i];
		}
		return total;
	}

	/**
	 * This function returns array of dice result in descending order
	 * 
	 * @return sortedRevDiceResult dice result in descending order.
	 */
	public int[] getDescSortedDiceResult() {

		for (int i = 0; i < 6; i++) {
			int value = getDiceRollResult();
			sortedRevDiceList[i] = value;
		}
		Arrays.sort(sortedRevDiceList);
		for (int i = 0; i < sortedRevDiceList.length / 2; i++) {
			int temp = sortedRevDiceList[i];
			sortedRevDiceList[i] = sortedRevDiceList[sortedRevDiceList.length
					- 1 - i];
			sortedRevDiceList[sortedRevDiceList.length - 1 - i] = temp;
		}
		return sortedRevDiceList;
	}

	/**
	 * 
	 * Setting the counter
	 * 
	 * @param counter
	 */
	public void setCounter(int counter) {
		this.counter = counter;
	}

	/**
	 * Setting the max dice value
	 * 
	 * @param maxDiceValue
	 */
	public void maxDiceValue(int maxDiceValue) {
		this.maxDiceValue = maxDiceValue;
	}

}
